class Event < ActiveRecord::Base
  
  HUMC_EVENT = 'HUMC_NOTIFICATION_SMS'
  CAMPAIGN_EVENT = 'CAMPAIGN_EVENT'
  AFTER_LOGIN_SURVEY = 'AFTER_LOGIN_SURVEY'
  INVITED_PATIENT_REMINDER = 'INVITED_PATIENT_REMINDER'
  SEND_REMINDER_NO_LOGIN = 'SEND_REMINDER_NO_LOGIN'
  SEND_REMINDER_NO_LOGIN_STUDY = 'SEND_REMINDER_NO_LOGIN_STUDY'
  SEND_REMINDER_FOR_RESET_PASSWORD = 'SEND_REMINDER_FOR_RESET_PASSWORD'
  SEND_RESET_REMINDER_ON_SUNDAY = 'SEND_RESET_REMINDER_ON_SUNDAY'
  REMIND_LOGIN_ADD_NEW_TAB = 'REMIND_LOGIN_ADD_NEW_TAB'
  SEND_SURVEY_REMINDER = 'SEND_SURVEY_REMINDER'
  AUTO_RESPOND_SMS= 'AUTO_RESPOND_SMS'
  AUTO_RESPOND_NO_KEYWORD_SMS='AUTO_RESPOND_NO_KEYWORD_SMS'
  SURVEY_FINISH_GREETINGS='SURVEY_FINISH_GREETINGS'
  DECLINE_STUDY="DECLINE_STUDY"
  WITHDRAW_STUDY="WITHDRAW_STUDY"
  STUDY_COMPLETED="STUDY_COMPLETED"
  NO_ACTIVITY_REMINDER_ADHOC='NO_ACTIVITY_REMINDER_ADHOC'
  PATIENT_INVITE_ADHOC='PATIENT_INVITE_ADHOC'
  STUDY_OVER='STUDY_OVER'
  INVITED_PATIENT_WATCHED_ADHOC_REMINDER='INVITED_PATIENT_WATCHED_ADHOC_REMINDER'
  NO_ACTIVITY_REMINDER_WATCHED_ADHOC='NO_ACTIVITY_REMINDER_WATCHED_ADHOC'
  PATIENT_INVITE_ADHOC_REMINDER='PATIENT_INVITE_ADHOC_REMINDER'
  ENROL_FOLLOW_UP='ENROL_FOLLOW_UP'
  ACCEPT_STUDY_COMMUNICATION='ACCEPT_STUDY_COMMUNICATION'
  ASSIGNED_TOPIC_NOTIFICATION='ASSIGNED_TOPIC_NOTIFICATION'
end
